// white_fronted/src/views/Login.tsx
import { useState } from 'react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { useAppDispatch } from '@/store/hooks'
import { setAuthToken, setUserInfo } from '@/store/authSlice'
import { login as loginApi, getCurrentUser } from '@/api/auth'

export default function Login() {
  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')

  const navigate = useNavigate()
  const [searchParams] = useSearchParams()
  const dispatch = useAppDispatch()

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!username.trim()) { setError('请输入用户名'); return }
    if (!password) { setError('请输入密码'); return }
    setError('')
    setLoading(true)

    try {
      const res: any = await loginApi({ username: username.trim(), password })
      if (res?.token) {
        dispatch(setAuthToken(res.token))
        try {
          const info: any = await getCurrentUser()
          if (info) {
            dispatch(setUserInfo({
              username: info.username ?? info.nickname ?? username,
              avatar: info.avatar ?? '',
              roles: info.roles ?? [],
            }))
          }
        } catch { /* ignore */ }
        const redirect = searchParams.get('redirect') || '/admin'
        navigate(redirect, { replace: true })
      } else {
        setError(res?.message || '登录失败')
      }
    } catch (e: any) {
      setError(e?.message || '登录失败，请检查用户名和密码')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="flex min-h-screen items-center justify-center bg-surface-soft p-4 sm:p-15">
      <div className="flex w-full max-w-[960px] overflow-hidden rounded-2xl bg-canvas shadow-lg">
        <div className="hidden flex-1 flex-col items-center justify-center gap-5 bg-surface-soft px-15 py-15 md:flex">
          <div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-primary/15">
            <span className="font-brand text-3xl text-primary">Y</span>
          </div>
          <h1 className="font-brand text-2xl text-body-strong">YoyuEN 知识库</h1>
          <p className="text-sm text-muted">基于 RAG 技术的智能问答系统</p>
        </div>

        <div className="flex flex-1 flex-col justify-center px-8 py-12 sm:px-15">
          <h2 className="mb-8 text-xl font-semibold text-body-strong">欢迎回来</h2>
          <form onSubmit={handleLogin} className="flex flex-col gap-4">
            <input
              type="text" value={username}
              onChange={(e) => setUsername(e.target.value)}
              placeholder="请输入用户名"
              className="h-11 rounded-lg border border-hairline bg-canvas px-4 text-sm text-body outline-none placeholder:text-muted-soft focus:border-primary"
            />
            <input
              type="password" value={password}
              onChange={(e) => setPassword(e.target.value)}
              placeholder="请输入密码"
              className="h-11 rounded-lg border border-hairline bg-canvas px-4 text-sm text-body outline-none placeholder:text-muted-soft focus:border-primary"
            />
            {error && <p className="text-xs text-error">{error}</p>}
            <button
              type="submit" disabled={loading}
              className="mt-2 h-11 rounded-lg bg-primary text-sm font-medium text-primary-foreground transition-colors hover:bg-primary-active disabled:cursor-not-allowed disabled:bg-primary-disabled disabled:text-muted"
            >
              {loading ? '登录中...' : '登录'}
            </button>
          </form>
        </div>
      </div>

      <div className="absolute top-8 flex items-center gap-2 md:hidden">
        <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/15">
          <span className="font-brand text-xl text-primary">Y</span>
        </div>
        <span className="font-brand text-lg text-body-strong">YoyuEN</span>
      </div>
    </div>
  )
}

// Fronted/src/views/Login.vue
<template>
  <div class="login-container">
    <div class="login-card">
      <!-- 左侧介绍区 -->
      <div class="left-section">
        <div class="logo">
          <div class="logo-icon">Y</div>
        </div>
        <h1 class="brand-name">YoyuEN 知识库</h1>
        <p class="brand-desc">基于RAG技术的智能问答系统</p>
      </div>

      <!-- 右侧登录表单 -->
      <div class="right-section">
        <div class="login-form">
          <h2 class="login-title">欢迎回来</h2>

          <div class="form-group">
            <input
              v-model="loginForm.username"
              type="text"
              class="form-input"
              placeholder="请输入用户名"
              @keyup.enter="handleLogin"
            />
          </div>

          <div class="form-group">
            <input
              v-model="loginForm.password"
              type="password"
              class="form-input"
              placeholder="请输入密码"
              @keyup.enter="handleLogin"
            />
          </div>

          <button class="login-button" :disabled="loading" @click="handleLogin">
            {{ loading ? '登录中...' : '登录' }}
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { ElMessage } from 'element-plus'
import { login } from '@/api/auth.js'
import { setToken } from '@/utils/auth.js'

const router = useRouter()
const route = useRoute()

const loginForm = ref({
  username: '',
  password: ''
})

const loading = ref(false)

const handleLogin = async () => {
  // 表单验证
  if (!loginForm.value.username) {
    ElMessage.warning('请输入用户名')
    return
  }
  if (!loginForm.value.password) {
    ElMessage.warning('请输入密码')
    return
  }

  loading.value = true

  try {
    const response = await login(loginForm.value)

    if (response.code === 200 && response.data.token) {
      // 保存 token
      setToken(response.data.token)

      // 显示成功提示
      ElMessage.success('登录成功')

      // 跳转到原目标页面或后台首页
      const redirect = route.query.redirect || '/admin'
      setTimeout(() => {
        router.push(redirect)
      }, 500)
    } else {
      ElMessage.error(response.message || '登录失败')
    }
  } catch (error) {
    ElMessage.error(error.message || '登录失败，请检查用户名和密码')
  } finally {
    loading.value = false
  }
}
</script>

<style scoped>
.login-container {
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: 100vh;
  background: #f5f5f5;
  padding: 60px;
}

.login-card {
  display: flex;
  width: 960px;
  height: 640px;
  background: #ffffff;
  border-radius: 16px;
  box-shadow: 0 4px 24px rgba(0, 0, 0, 0.08);
  overflow: hidden;
}

/* 左侧介绍区 */
.left-section {
  flex: 1;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  background: #fafafa;
  padding: 60px;
  gap: 20px;
  border-radius: 16px 0 0 16px;
}

.logo {
  width: 64px;
  height: 64px;
  background: #e8eaf6;
  border-radius: 16px;
  display: flex;
  justify-content: center;
  align-items: center;
}

.logo-icon {
  font-size: 32px;
  font-weight: 600;
  color: #5c6bc0;
  font-family: Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
}

.brand-name {
  font-size: 24px;
  font-weight: 600;
  color: #2c3e50;
  margin: 0;
  font-family: Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
}

.brand-desc {
  font-size: 14px;
  color: #95a5a6;
  text-align: center;
  margin: 0;
  font-family: Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
}

/* 右侧登录表单 */
.right-section {
  flex: 1;
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 80px;
  border-radius: 0 16px 16px 0;
}

.login-form {
  width: 360px;
  display: flex;
  flex-direction: column;
  gap: 24px;
}

.login-title {
  font-size: 24px;
  font-weight: 600;
  color: #2c3e50;
  margin: 0;
  font-family: Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
}

.form-group {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.form-input {
  width: 100%;
  height: 48px;
  padding: 0 16px;
  background: #f8f9fa;
  border: none;
  border-radius: 8px;
  font-size: 14px;
  color: #2c3e50;
  font-family: Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
  outline: none;
  transition: background 0.2s;
}

.form-input::placeholder {
  color: #adb5bd;
}

.form-input:focus {
  background: #e9ecef;
}

.login-button {
  width: 100%;
  height: 52px;
  background: #ffeaa7;
  border: none;
  border-radius: 10px;
  font-size: 16px;
  font-weight: 500;
  color: #2c3e50;
  cursor: pointer;
  transition: all 0.2s;
  font-family: Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
}

.login-button:hover:not(:disabled) {
  background: #ffd97d;
  transform: translateY(-1px);
}

.login-button:active:not(:disabled) {
  transform: translateY(0);
}

.login-button:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}
</style>
