// white_fronted/src/views/Profile.tsx
import { useEffect, useRef, useState } from 'react'
import { fetchPhotoList } from '@/api/photo'
import { fetchProfileDetail } from '@/api/profile'
import defaultAvatar from '@/assets/picture/YoyuEN.png'

const ROW_HEIGHT = 200

interface Photo {
  id: string | number
  url: string
  description?: string
  displayWidth?: string
}

export default function Profile() {
  const [profile, setProfile] = useState({
    nickname: 'YoyuEN',
    avatar: defaultAvatar,
    signature: '宁鸣而死，不默而生！',
    welcomeText: '欢迎来到我的知识空间！这里记录着我的学习历程、技术探索和生活感悟。希望我的分享能给你带来一些启发和帮助。',
    school: '北方民族大学 · 软件工程',
    email: '15839393171@163.com',
    location: '北京 · 昌平',
  })
  const [techStack, setTechStack] = useState([
    'Vue.js', 'React', 'TypeScript', 'Node.js', 'Python', 'Java', 'MySQL', 'Git',
  ])
  const [tags, setTags] = useState([
    '玄不救非,氪不改命', '男神', '手工', '天然呆', '篮球', 'Running', 'Gym',
  ])
  const [photos, setPhotos] = useState<Photo[]>([])

  useEffect(() => {
    fetchPhotoList()
      .then((res: any) => setPhotos(res?.data ?? []))
      .catch(() => {})

    fetchProfileDetail()
      .then((res: any) => {
        const data = res?.data
        if (data) {
          setProfile((prev) => ({
            nickname: data.nickname || prev.nickname,
            avatar: data.avatar || prev.avatar,
            signature: data.signature || prev.signature,
            welcomeText: data.welcomeText || prev.welcomeText,
            school: data.school || prev.school,
            email: data.email || prev.email,
            location: data.location || prev.location,
          }))
          if (data.techStack) {
            try {
              const parsed = JSON.parse(data.techStack)
              if (Array.isArray(parsed) && parsed.length > 0) setTechStack(parsed)
            } catch {}
          }
          if (data.tags) {
            try {
              const parsed = JSON.parse(data.tags)
              if (Array.isArray(parsed) && parsed.length > 0) setTags(parsed)
            } catch {}
          }
        }
      })
      .catch(() => {})
  }, [])

  return (
    <div className="min-h-screen bg-canvas px-6 py-24 sm:px-12">
      <div className="mx-auto max-w-5xl">
        {/* 个人信息头部 */}
        <div className="flex flex-col items-center gap-6 pb-10">
          <div className="relative">
            <img
              src={profile.avatar}
              alt={profile.nickname}
              className="h-24 w-24 rounded-full object-cover ring-4 ring-hairline-soft"
            />
          </div>
          <div className="text-center">
            <h1 className="text-2xl font-semibold text-body-strong">{profile.nickname}</h1>
            <p className="mt-1 text-sm text-muted">{profile.signature}</p>
          </div>
          <p className="max-w-xl text-center text-sm leading-relaxed text-body">
            {profile.welcomeText}
          </p>
        </div>

        {/* 详情卡片网格 */}
        <div className="grid gap-4 sm:grid-cols-3">
          <div className="rounded-xl border border-hairline bg-surface-card p-5">
            <h4 className="mb-3 text-sm font-semibold text-body-strong">个人信息</h4>
            <div className="space-y-2 text-sm text-body">
              <p>{profile.school}</p>
              <p>{profile.email}</p>
              <p>{profile.location}</p>
            </div>
          </div>
          <div className="rounded-xl border border-hairline bg-surface-card p-5">
            <h4 className="mb-3 text-sm font-semibold text-body-strong">技术栈</h4>
            <div className="flex flex-wrap gap-1.5">
              {techStack.map((t) => (
                <span key={t} className="rounded-full bg-surface-soft px-2.5 py-1 text-xs text-body">
                  {t}
                </span>
              ))}
            </div>
          </div>
          <div className="rounded-xl border border-hairline bg-surface-card p-5">
            <h4 className="mb-3 text-sm font-semibold text-body-strong">个人标签</h4>
            <div className="flex flex-wrap gap-1.5">
              {tags.map((t) => (
                <span key={t} className="rounded-full bg-surface-soft px-2.5 py-1 text-xs text-body">
                  {t}
                </span>
              ))}
            </div>
          </div>
        </div>

        {/* 照片墙 */}
        {photos.length > 0 && (
          <div className="mt-10">
            <h3 className="mb-4 text-lg font-semibold text-body-strong">照片墙</h3>
            <div className="flex flex-wrap gap-2">
              {photos.map((photo, i) => (
                <PhotoItem key={photo.id ?? i} photo={photo} index={i} />
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  )
}

function PhotoItem({ photo, index }: { photo: Photo; index: number }) {
  const [displayWidth, setDisplayWidth] = useState<string | undefined>(photo.displayWidth)
  const ref = useRef<HTMLImageElement | null>(null)

  const handleLoad = () => {
    const img = ref.current
    if (img && !displayWidth) {
      const ratio = img.naturalWidth / (img.naturalHeight || 1)
      setDisplayWidth(`${ROW_HEIGHT * ratio}px`)
    }
  }

  return (
    <div
      className="overflow-hidden rounded-lg opacity-0 animate-[fadeIn_0.5s_ease-out_forwards]"
      style={{ animationDelay: `${index * 0.1}s`, width: displayWidth || 'auto', height: ROW_HEIGHT }}
    >
      <img
        ref={ref}
        src={photo.url}
        alt={photo.description || '照片'}
        className="h-full w-full object-cover"
        onLoad={handleLoad}
      />
    </div>
  )
}

// Fronted/src/views/Profile.vue
<template>
  <div class="profile-container">
    <div class="profile-header">
      <div class="user-info-container">
        <!-- 头像和基本信息 -->
        <div class="user-header">
          <div class="avatar">
            <img :src="profile.avatar" alt="用户头像" />
          </div>
          <div class="user-basic">
            <h3>{{ profile.nickname }}</h3>
            <p class="user-signature">{{ profile.signature }}</p>
          </div>
        </div>
        <div class="welcome-container">
           <p class="user-welcome">{{ profile.welcomeText }}</p>
        </div>
        <!-- 详细信息卡片 -->
        <div class="info-cards">
          <div class="info-card">
            <h4>个人信息</h4>
            <div class="card-content">
              <div class="info-row">
                <span>{{ profile.school }}</span>
              </div>
              <div class="info-row">
                <span>{{ profile.email }}</span>
              </div>
              <div class="info-row">
                <span>{{ profile.location }}</span>
              </div>
            </div>
          </div>

          <div class="info-card">
            <h4>技术栈</h4>
            <div class="card-content">
              <div class="tags-wrapper">
                <span v-for="tech in techStack" :key="tech" class="tech-tag">{{ tech }}</span>
              </div>
            </div>
          </div>

          <div class="info-card">
            <h4>个人标签</h4>
            <div class="card-content">
              <div class="tags-wrapper">
                <span v-for="tag in tags" :key="tag" class="tech-tag">{{ tag }}</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="profile-content">
      <div class="profile-row">
      </div>

      <!-- 照片墙 -->
      <div class="profile-item">
        <h3>照片墙</h3>
        <div class="photo-wall-container">
          <div
            v-for="(photo, index) in photos"
            :key="photo.id"
            class="photo-item"
            :style="{
              animationDelay: `${index * 0.1}s`,
              width: photo.displayWidth || 'auto'
            }"
          >
            <n-image
              :src="photo.url"
              :alt="photo.description || '照片'"
              @load="(e) => handleImageLoad(e, photo)"
            />
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
<script setup lang="ts">
import { ref, onMounted } from "vue";
import { ElMessage } from 'element-plus'
import { fetchPhotoList } from "../api/photo/photo.js";
import { fetchProfileDetail } from "../api/profile/profile.js";

const photos = ref([]);

const ROW_HEIGHT = 200; // 固定行高

// 个人资料
const profile = ref({
  nickname: 'YoyuEN',
  avatar: '/src/assets/picture/YoyuEN.png',
  signature: '宁鸣而死，不默而生！',
  welcomeText: '欢迎来到我的知识空间！这里记录着我的学习历程、技术探索和生活感悟。希望我的分享能给你带来一些启发和帮助。',
  school: '北方民族大学 · 软件工程',
  email: '15839393171@163.com',
  location: '北京 · 昌平',
})

// 技术栈
const techStack = ref([
  "Vue.js",
  "React",
  "TypeScript",
  "Node.js",
  "Python",
  "Java",
  "MySQL",
  "Git"
]);

// 标签
const tags = ref([
  "玄不救非,氪不改命",
  "男神",
  "手工",
  "天然呆",
  "篮球",
  "Running",
  "Gym",
]);

// 图片加载完成后计算宽度
const handleImageLoad = (event, photo) => {
  const img = event.target;
  const aspectRatio = img.naturalWidth / img.naturalHeight;
  const calculatedWidth = ROW_HEIGHT * aspectRatio;
  photo.displayWidth = `${calculatedWidth}px`;
};

const loadProfile = async () => {
  try {
    const res = await fetchProfileDetail()
    if (res.data) {
      const data = res.data
      profile.value = {
        nickname: data.nickname || profile.value.nickname,
        avatar: data.avatar || profile.value.avatar,
        signature: data.signature || profile.value.signature,
        welcomeText: data.welcomeText || profile.value.welcomeText,
        school: data.school || profile.value.school,
        email: data.email || profile.value.email,
        location: data.location || profile.value.location,
      }
      if (data.techStack) {
        try {
          const parsed = JSON.parse(data.techStack)
          if (Array.isArray(parsed) && parsed.length > 0) {
            techStack.value = parsed
          }
        } catch {
          // 解析失败则保持默认值
        }
      }
      if (data.tags) {
        try {
          const parsed = JSON.parse(data.tags)
          if (Array.isArray(parsed) && parsed.length > 0) {
            tags.value = parsed
          }
        } catch {
          // 解析失败则保持默认值
        }
      }
    }
  } catch (e) {
    console.error("获取个人资料失败", e)
  }
}

onMounted(async () => {
  try {
    const res = await fetchPhotoList();
    photos.value = res.data || [];
  } catch (e) {
    console.error("获取照片列表失败", e);
  }
  await loadProfile()
});
</script>
<style scoped>
/* 头像浮动动画 */
@keyframes float {
  0%, 100% {
    transform: translateY(0px);
  }
  50% {
    transform: translateY(-10px);
  }
}

/* 光环流动动画 */
@keyframes shimmer {
  0% {
    background-position: -200% center;
  }
  100% {
    background-position: 200% center;
  }
}

/* 照片墙淡入动画 */
@keyframes fadeInUp {
  from {
    opacity: 0;
    transform: translateY(30px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

.profile-container {
  width: 100%;
  position: relative;
}

.profile-header {
  position: sticky;
  top: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  width: 100%;
  height: 700px;
  background: url("/src/assets/picture/image.png") no-repeat center center;
  background-size: cover;
  padding: 80px;
  z-index: 1;
}

.user-info-container {
  max-width: 1200px;
  width: 100%;
  display: flex;
  flex-direction: column;
  gap: 30px;
  position: relative;
  z-index: 1;
}

.user-header {
  display: flex;
  align-items: flex-start;
  gap: 40px;
  margin-bottom: 30px;
}

.user-basic {
  flex: 1;
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.user-basic h3 {
  font-family: "快看世界体";
  font-size: 36px;
  color: rgba(255, 255, 255, 0.98);
  text-shadow: 0 3px 12px rgba(0, 0, 0, 0.4);
  margin: 0;
  letter-spacing: 1px;
}

.user-signature {
  font-size: 18px;
  color: rgba(255, 255, 255, 0.92);
  text-shadow: 0 2px 6px rgba(0, 0, 0, 0.4);
  font-style: italic;
  margin: 0;
  font-weight: 500;
}

.welcome-container {
  width: 100%;
  animation: fadeInUp 0.8s ease-out 0.3s backwards;
}

@keyframes fadeInUp {
  from {
    opacity: 0;
    transform: translateY(20px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

.user-welcome {
  font-size: 15px;
  color: rgba(255, 255, 255, 0.9);
  text-shadow: 0 2px 6px rgba(0, 0, 0, 0.4);
  line-height: 2;
  margin: 0;
  padding: 20px 24px;
  background: rgba(255, 255, 255, 0.12);
  backdrop-filter: blur(15px);
  border-radius: 16px;
  border: 1px solid rgba(255, 255, 255, 0.25);
  box-shadow: 0 4px 16px rgba(0, 0, 0, 0.15);
  transition: all 0.3s ease;
  position: relative;
  overflow: hidden;
}

.user-welcome::before {
  content: '';
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  height: 1px;
  background: linear-gradient(90deg, transparent, rgba(255, 255, 255, 0.3), transparent);
}

.user-welcome:hover {
  background: rgba(255, 255, 255, 0.15);
  transform: translateY(-2px);
  box-shadow: 0 6px 20px rgba(0, 0, 0, 0.2);
}

.info-cards {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
  gap: 24px;
}

.info-card {
  background: rgba(255, 255, 255, 0.15);
  backdrop-filter: blur(20px);
  border-radius: 16px;
  padding: 20px;
  border: 1px solid rgba(255, 255, 255, 0.2);
  transition: all 0.3s ease;
}

.info-card:hover {
  background: rgba(255, 255, 255, 0.2);
  transform: translateY(-4px);
  box-shadow: 0 8px 24px rgba(0, 0, 0, 0.2);
}

.info-card h4 {
  font-size: 16px;
  color: rgba(255, 255, 255, 0.95);
  text-shadow: 0 2px 4px rgba(0, 0, 0, 0.3);
  margin: 0 0 16px 0;
  font-weight: 600;
}

.card-content {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.info-row {
  display: flex;
  align-items: center;
  gap: 10px;
  font-size: 14px;
  color: rgba(255, 255, 255, 0.9);
  text-shadow: 0 2px 4px rgba(0, 0, 0, 0.3);
}

.tags-wrapper {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
}

.avatar {
  width: 120px;
  height: 120px;
  border-radius: 50%;
  border: 4px solid white;
  position: relative;
  animation: float 3s ease-in-out infinite;
  transition: all 0.4s ease;
  cursor: pointer;
  flex-shrink: 0;
}

/* 头像光环效果 */
.avatar::before {
  content: "";
  position: absolute;
  inset: -8px;
  border-radius: 50%;
  background: linear-gradient(45deg, #667eea, #764ba2, #f093fb, #4facfe, #667eea);
  background-size: 300% 300%;
  opacity: 0;
  z-index: -1;
  transition: opacity 0.4s ease;
  animation: shimmer 3s linear infinite;
  filter: blur(10px);
}

.avatar:hover::before {
  opacity: 0.8;
}

.avatar:hover {
  transform: scale(1.1) rotate(5deg);
  box-shadow: 0 10px 30px rgba(0, 0, 0, 0.3);
}

.avatar img {
  width: 100%;
  height: 100%;
  border-radius: 50%;
  transition: all 0.4s ease;
}

.avatar:hover img {
  filter: brightness(1.1);
}

.tech-tag {
  background: rgba(255, 255, 255, 0.25);
  backdrop-filter: blur(10px);
  padding: 6px 14px;
  border-radius: 20px;
  font-size: 13px;
  color: white;
  text-shadow: 0 1px 2px rgba(0, 0, 0, 0.3);
  transition: all 0.3s ease;
  cursor: pointer;
}

.tech-tag:hover {
  background: rgba(255, 255, 255, 0.35);
  transform: translateY(-2px);
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.2);
}

.profile-content {
  position: relative;
  margin-top: -50px;
  background-color: white;
  border-radius: 25px;
  padding: 20px 80px;
  box-shadow: 0 2px 12px rgba(0, 0, 0, 0.08);
  z-index: 2;
  min-height: 100vh;
}

.profile-row {
  display: flex;
  gap: 40px;
  align-items: flex-start;
  margin: 0 50px;
}

.profile-item {
  margin: 0 50px;
}

.profile-item--data {
  flex-shrink: 0;
  margin: 0;
  width: 1000px;
}

.profile-item--heatmap {
  flex: 1;
  margin: 0;
  min-width: 0;
}

.profile-item h3 {
  color: #333;
  padding: 20px 0;
  border-bottom: 1px solid #e0e0e0;
  margin-bottom: 20px;
}

.heatmap-container {
  width: 100%;
}

.website-data {
  display: flex;
  justify-content: space-around;
  gap: 40px;
  padding: 20px 0;
}

.data-item {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 10px;
}

.data-number {
  font-size: 32px;
  font-weight: bold;
  color: #333;
}

.data-label {
  font-size: 14px;
  color: #666;
}

.photo-wall-container {
  display: flex;
  flex-wrap: wrap;
  gap: 16px;
  padding: 10px 0;
  align-items: flex-start;
}

.photo-item {
  position: relative;
  overflow: hidden;
  border-radius: 12px;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
  transition: all 0.3s ease;
  animation: fadeInUp 0.6s ease-out backwards;
  cursor: pointer;
  height: 200px; /* 固定行高 */
  flex-grow: 0;
  flex-shrink: 0;
}

.photo-item:hover {
  transform: translateY(-8px) scale(1.02);
  box-shadow: 0 12px 24px rgba(0, 0, 0, 0.15);
}

.photo-item::before {
  content: "";
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: linear-gradient(135deg, rgba(102, 126, 234, 0.1), rgba(118, 75, 162, 0.1));
  opacity: 0;
  transition: opacity 0.3s ease;
  z-index: 1;
  pointer-events: none;
}

.photo-item:hover::before {
  opacity: 1;
}

.photo-item :deep(.n-image) {
  width: 100%;
  height: 100%;
  display: block;
}

.photo-item :deep(.n-image img) {
  width: 100%;
  height: 100%;
  object-fit: cover;
  transition: transform 0.3s ease;
}

.photo-item:hover :deep(.n-image img) {
  transform: scale(1.05);
}

.photo-items {
  width: 100%;
  display: flex;
  flex-wrap: wrap;
  justify-content: flex-start;
  gap: 20px;
}

.n-image {
  width: 100%;
  height: 100%;
  border-radius: 10px;
}
</style>
