// Fronted/src/views/Content.vue
<template>
  <div class="page-wrapper">

    <!-- 左侧：可滚动内容区 -->
    <div class="content-main">

      <!-- 推荐内容 -->
      <section class="module fade-in">
        <div class="module-header">
          <h2 class="module-title">推荐内容</h2>
          <span class="module-more">查看更多</span>
        </div>
        <div class="recommend-grid">
          <div v-for="item in recommendList" :key="item.id" class="recommend-card fade-in" @click="goToDetail(item, item.category)">
            <div class="rc-image">
              <img :src="item.cover" :alt="item.title" />
              <div class="rc-overlay"></div>
              <div class="rc-time">{{ item.date }}</div>
              <div class="rc-avatar">
                <img src="/src/assets/picture/YoyuEN.png" alt="Author" />
              </div>
              <div class="rc-comment-count">
                <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                  <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"></path>
                </svg>
                <span>{{ item.comments }}</span>
              </div>
              <div class="rc-content">
                <h3 class="rc-title">{{ item.title }}</h3>
                <p class="rc-summary">{{ item.desc.length > 40 ? item.desc.slice(0, 40) + '...' : item.desc }}</p>
                <div class="rc-tags">
                  <span class="rc-tag">{{ item.category }}</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <!-- 内容模块 -->
      <section v-for="category in contentCategories" :key="category.type" class="module fade-in">
        <div class="module-header">
          <h2 class="module-title">{{ category.title }}</h2>
          <span class="module-count">{{ category.count }} 篇</span>
        </div>
        <div class="list">
          <div v-for="item in category.list" :key="item.id" class="list-item fade-in" @click="goToDetail(item, category.type)">
            <div class="item-thumb" :class="{ 'video-thumb': category.type === 'video' }">
              <img :src="item.cover" :alt="item.title" />
              <span v-if="category.type === 'video'" class="play-icon">
                <svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor">
                  <polygon points="5 3 19 12 5 21 5 3"></polygon>
                </svg>
              </span>
            </div>
            <div class="item-body">
              <div class="item-title">{{ item.title }}</div>
              <div class="item-desc">{{ item.desc }}</div>
              <div class="item-meta">
                <span class="meta-date">{{ item.date }}</span>
                <span class="meta-divider">·</span>
                <span class="meta-comment">
                  <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                    <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"></path>
                  </svg>
                  {{ item.comments }}
                </span>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>

    <!-- 右侧：固定边栏 -->
    <aside class="sidebar">

      <!-- 个人信息卡 -->
      <div class="sidebar-card profile-card fade-in">
        <div class="profile-avatar">
          <img src="/src/assets/picture/YoyuEN.png" alt="YoyuEN" />
        </div>
        <div class="profile-name">YoyuEN</div>
        <div class="profile-sign">宁鸣而死，不默而生</div>
        <div class="profile-bio">
          北方民族大学 · 软件工程<br />
          热爱技术、游戏与生活，记录一切值得留下的东西。
        </div>
        <div class="profile-stats">
          <div class="stat-item">
            <span class="stat-num">{{ siteStats.contentCount }}</span>
            <span class="stat-label">文章</span>
          </div>
          <div class="stat-divider"></div>
          <div class="stat-item">
            <span class="stat-num">{{ siteStats.commentCount }}</span>
            <span class="stat-label">评论</span>
          </div>
        </div>
      </div>

      <!-- 每日碎碎念 -->
      <div class="sidebar-card fade-in">
        <div class="sidebar-card-title">每日碎碎念</div>
        <div class="murmur-list">
          <div v-for="item in murmurList" :key="item.id" class="murmur-item">
            <div class="murmur-text">{{ item.text }}</div>
            <div class="murmur-date">{{ item.date }}</div>
          </div>
        </div>
      </div>

    </aside>

  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { fetchRecommendContent, fetchContentByCategory, fetchContentCategories, fetchContentStats } from '@/api/content/content.js'
import { fetchLatestMurmur } from '@/api/murmur/murmur.js'
import { initFadeIn } from '@/js/fadeIn'

const router = useRouter()

const goToDetail = (item, type) => {
  router.push({ name: 'ContentDetail', params: { type, id: item.id } })
}

// 将后端 ContentVO 字段归一化为模板期望的字段
function normalizeContent(item) {
  return {
    ...item,
    desc: item.description ?? item.desc ?? '',
    comments: item.commentCount ?? item.comments ?? 0,
    date: item.createTime ?? item.date ?? '',
  }
}

const recommendList = ref([])
const murmurList = ref([])
const contentCategories = ref([])
const siteStats = ref({ contentCount: 0, commentCount: 0 })

onMounted(async () => {
  const [categoriesRes, recommend, murmurs, statsRes] = await Promise.allSettled([
    fetchContentCategories(),
    fetchRecommendContent(),
    fetchLatestMurmur(5),
    fetchContentStats(),
  ])

  if (recommend.status === 'fulfilled') {
    recommendList.value = (recommend.value.data || []).map(normalizeContent)
  }
  if (murmurs.status === 'fulfilled') {
    murmurList.value = (murmurs.value.data || []).map(m => ({
      ...m,
      text: m.content ?? m.text ?? '',
      date: m.createTime ?? m.date ?? '',
    }))
  }
  if (statsRes.status === 'fulfilled' && statsRes.value.data) {
    siteStats.value = statsRes.value.data
  }

  // 根据后端返回的分类动态加载，没有内容的分类不显示
  // 接口失败时降级为固定顺序的分类列表（名称也由后端提供）
  const fallbackCategories = [
    { type: 'article', name: '文章', count: 0 },
    { type: 'game', name: '游戏', count: 0 },
    { type: 'study', name: '学习', count: 0 },
    { type: 'video', name: '视频', count: 0 },
  ]
  const cats = (categoriesRes.status === 'fulfilled' && categoriesRes.value.data?.length > 0)
    ? categoriesRes.value.data
    : fallbackCategories
  const results = await Promise.allSettled(cats.map(cat => fetchContentByCategory(cat.type)))
  contentCategories.value = cats
    .map((cat, i) => ({
      type: cat.type,
      title: cat.name,
      count: cat.count || 0,
      list: results[i].status === 'fulfilled' ? (results[i].value.data || []).map(normalizeContent).slice(0, 5) : [],
    }))
    .filter(c => c.list.length > 0)

  // 数据加载完成后触发淡入动画
  setTimeout(() => {
    initFadeIn()
  }, 100)
})
</script>

<style scoped>
/* ---- 整体布局 ---- */
.page-wrapper {
  display: flex;
  gap: 24px;
  margin: 36px auto;
  padding: 40px 24px 0px;
  align-items: flex-start;
  background: #fff;
  min-height: calc(100vh - 90px);
}

.module {
  margin-bottom: 40px;
  }

/* ---- 左侧内容 ---- */
.content-main {
  flex: 1;
  min-width: 0;
  padding: 20px;
  border: 1px solid #ebebeb;
  border-radius: 10px;
}

/* ---- 模块公共 ---- */

.module-header {
  display: flex;
  align-items: baseline;
  justify-content: space-between;
  padding-bottom: 12px;
  border-bottom: 1px solid #ebebeb;
  margin-bottom: 20px;
}

.module-title {
  font-size: 17px;
  font-weight: 600;
  color: #1a1a1a;
  margin: 0;
}

.module-more {
  font-size: 13px;
  color: #999;
  transition: color 0.2s;
}

.module-count {
  font-size: 13px;
  color: #999;
}

/* ---- 推荐网格 ---- */
.recommend-grid {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 16px;
}

.recommend-card {
  border-radius: 8px;
  overflow: hidden;
  cursor: pointer;
  box-shadow: 0 2px 12px rgba(0, 0, 0, 0.1);
  transition: all 0.3s ease;
}

.recommend-card:hover {
  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.15);
  transform: translateY(-2px);
}

.rc-image {
  position: relative;
  width: 100%;
  height: 400px;
  overflow: hidden;
  background: #f0f0f0;
}

.rc-image img {
  width: 100%;
  height: 100%;
  object-fit: cover;
  transition: transform 0.3s ease;
}

.recommend-card:hover .rc-image img {
  transform: scale(1.05);
}

.rc-overlay {
  position: absolute;
  inset: 0;
  background: linear-gradient(to bottom, rgba(0,0,0,0) 0%, rgba(0,0,0,0.2) 50%, rgba(0,0,0,0.7) 100%);
  transition: background 0.3s ease;
}

.recommend-card:hover .rc-overlay {
  background: linear-gradient(to bottom, rgba(0,0,0,0) 0%, rgba(0,0,0,0.3) 50%, rgba(0,0,0,0.8) 100%);
}

.rc-time {
  position: absolute;
  top: 10px;
  right: 10px;
  background: rgba(0,0,0,0.3);
  backdrop-filter: blur(10px);
  color: #fff;
  padding: 4px 10px;
  border-radius: 4px;
  font-size: 12px;
  z-index: 2;
}

.rc-avatar {
  position: absolute;
  top: 10px;
  left: 10px;
  width: 32px;
  height: 32px;
  border-radius: 50%;
  overflow: hidden;
  z-index: 2;
  border: 2px solid rgba(255,255,255,0.8);
  box-shadow: 0 2px 4px rgba(0,0,0,0.2);
}

.rc-avatar img {
  width: 100%;
  height: 100%;
  object-fit: cover;
}

.rc-comment-count {
  position: absolute;
  top: 10px;
  right: 120px;
  display: flex;
  align-items: center;
  gap: 4px;
  color: #fff;
  font-size: 12px;
  background: rgba(0,0,0,0.3);
  backdrop-filter: blur(10px);
  padding: 4px 8px;
  border-radius: 4px;
  z-index: 2;
  opacity: 0;
  transform: translateY(-10px);
  transition: all 0.3s ease;
}

.recommend-card:hover .rc-comment-count {
  opacity: 1;
  transform: translateY(0);
}

.rc-content {
  padding: 16px;
}

.rc-title {
  margin: 0 0 10px;
  font-size: 14px;
  font-weight: 600;
  color: #fff;
  line-height: 1.4;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
  position: absolute;
  bottom: 36px;
  left: 16px;
  right: 16px;
  z-index: 2;
  transition: all 0.3s ease;
}

.rc-summary {
  margin: 0 0 10px;
  font-size: 12px;
  color: #e0e0e0;
  line-height: 1.5;
  position: absolute;
  bottom: 36px;
  left: 16px;
  right: 16px;
  z-index: 2;
  opacity: 0;
  transform: translateY(10px);
  transition: all 0.3s ease;
  pointer-events: none;
  display: -webkit-box;
  -webkit-line-clamp: 3;
  line-clamp: 3;
  -webkit-box-orient: vertical;
  overflow: hidden;
}

.recommend-card:hover .rc-title {
  opacity: 0;
  transform: translateY(-10px);
}

.recommend-card:hover .rc-summary {
  opacity: 1;
  transform: translateY(0);
}

.rc-tags {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
  position: absolute;
  bottom: 10px;
  left: 16px;
  right: 16px;
  z-index: 2;
}

.rc-tag {
  background: transparent;
  color: #fff;
  font-size: 11px;
  padding: 2px 8px;
}

/* ---- 列表通用 ---- */
.list {
  display: flex;
  flex-direction: column;
}

.list-item {
  display: flex;
  gap: 16px;
  padding: 16px 0;
  border-bottom: 1px solid #f2f2f2;
  cursor: pointer;
  transition: background 0.15s;
}

.list-item:last-child {
  border-bottom: none;
}

.list-item:hover {
  background: #fafafa;
  padding-left: 6px;
  padding-right: 6px;
  border-radius: 6px;
  margin: 0 -6px;
}

.item-thumb {
  flex-shrink: 0;
  width: 110px;
  height: 74px;
  border-radius: 6px;
  overflow: hidden;
  background: #f5f5f5;
  position: relative;
}

.item-thumb img {
  width: 100%;
  height: 100%;
  object-fit: cover;
}

.video-thumb .play-icon {
  position: absolute;
  inset: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  background: rgba(0, 0, 0, 0.3);
  color: #fff;
  opacity: 0;
  transition: opacity 0.2s;
}

.list-item:hover .video-thumb .play-icon {
  opacity: 1;
}

.item-body {
  flex: 1;
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  min-width: 0;
}

.item-title {
  font-size: 14px;
  font-weight: 600;
  color: #1a1a1a;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.item-desc {
  font-size: 12px;
  color: #888;
  line-height: 1.6;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
  flex: 1;
  margin: 4px 0;
}

.item-meta {
  display: flex;
  align-items: center;
  gap: 6px;
  font-size: 12px;
  color: #bbb;
}

.meta-comment {
  display: flex;
  align-items: center;
  gap: 3px;
}

.meta-date { color: #bbb; }
.meta-divider { color: #ddd; }

/* ---- 右侧固定边栏 ---- */
.sidebar {
  flex-shrink: 0;
  width: 300px;
  position: sticky;
  top: 76px;
  display: flex;
  flex-direction: column;
  gap: 16px;
}

.sidebar-card {
  border: 1px solid #ebebeb;
  border-radius: 10px;
  padding: 20px 16px;
  background: #fff;
}

/* 个人信息卡 */
.profile-card {
  display: flex;
  flex-direction: column;
  align-items: center;
  text-align: center;
  gap: 8px;
}

/* 头像浮动动画 */
@keyframes float {
  0%, 100% { transform: translateY(0px); }
  50%       { transform: translateY(-8px); }
}

/* 光环流动动画 */
@keyframes shimmer {
  0%   { background-position: -200% center; }
  100% { background-position:  200% center; }
}

.profile-avatar {
  width: 72px;
  height: 72px;
  border-radius: 50%;
  border: 2px solid rgba(255, 255, 255, 0.9);
  margin-bottom: 4px;
  position: relative;
  animation: float 3s ease-in-out infinite;
  transition: all 0.4s ease;
  cursor: pointer;
  flex-shrink: 0;
}

/* 光环层 */
.profile-avatar::before {
  content: '';
  position: absolute;
  inset: -6px;
  border-radius: 50%;
  background: linear-gradient(45deg, #667eea, #764ba2, #f093fb, #4facfe, #667eea);
  background-size: 300% 300%;
  opacity: 0;
  z-index: -1;
  transition: opacity 0.4s ease;
  animation: shimmer 3s linear infinite;
  filter: blur(8px);
}

.profile-avatar:hover::before {
  opacity: 0.8;
}

.profile-avatar:hover {
  transform: scale(1.1) rotate(5deg);
  box-shadow: 0 8px 24px rgba(0, 0, 0, 0.2);
}

.profile-avatar img {
  width: 100%;
  height: 100%;
  object-fit: cover;
  border-radius: 50%;
  transition: all 0.4s ease;
}

.profile-avatar:hover img {
  filter: brightness(1.1);
}

.profile-name {
  font-size: 15px;
  font-weight: 600;
  color: #1a1a1a;
}

.profile-sign {
  font-size: 12px;
  color: #999;
  font-style: italic;
}

.profile-bio {
  font-size: 12px;
  color: #888;
  line-height: 1.8;
  padding-top: 8px;
  border-top: 1px solid #f2f2f2;
  width: 100%;
  text-align: left;
}

.profile-stats {
  display: flex;
  align-items: center;
  justify-content: space-between;
  width: 100%;
  padding-top: 12px;
  border-top: 1px solid #f2f2f2;
  margin-top: 4px;
}

.stat-item {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 2px;
  flex: 1;
}

.stat-num {
  font-size: 15px;
  font-weight: 600;
  color: #1a1a1a;
}

.stat-label {
  font-size: 11px;
  color: #bbb;
}

.stat-divider {
  width: 1px;
  height: 28px;
  background: #ebebeb;
}

/* 碎碎念卡 */
.sidebar-card-title {
  font-size: 14px;
  font-weight: 600;
  color: #1a1a1a;
  margin-bottom: 14px;
  padding-bottom: 10px;
  border-bottom: 1px solid #ebebeb;
}

.murmur-list {
  display: flex;
  flex-direction: column;
  gap: 14px;
}

.murmur-item {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.murmur-text {
  font-size: 12px;
  color: #555;
  line-height: 1.7;
}

.murmur-date {
  font-size: 11px;
  color: #ccc;
}
</style>

// white_fronted/src/views/Content.tsx
import { useEffect, useRef, useState } from 'react'
import { Link } from 'react-router-dom'
import { BookOpen, MessageCircle } from 'lucide-react'
import { fetchRecommendContent, fetchContentByCategory, fetchContentCategories, fetchContentStats } from '@/api/content'
import { fetchLatestMurmur } from '@/api/murmur'
import { initFadeIn } from '@/utils/fadeIn'
import defaultAvatar from '@/assets/picture/YoyuEN.png'

interface ContentItem {
  id: string | number
  title: string
  desc: string
  cover?: string
  date?: string
  comments?: number
  category?: string
  contentType?: string
}

interface CategoryGroup {
  type: string
  title: string
  count: number
  list: ContentItem[]
}

function normalize(item: any): ContentItem {
  return {
    ...item,
    desc: item.description ?? item.desc ?? '',
    comments: item.commentCount ?? item.comments ?? 0,
    date: item.createTime ?? item.date ?? '',
    category: item.categoryName ?? item.category ?? '',
  }
}

function formatDate(dateStr?: string): string {
  if (!dateStr) return ''
  const d = new Date(dateStr.replace(/-/g, '/'))
  if (isNaN(d.getTime())) return dateStr.slice(0, 10)
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`
}

export default function Content() {
  const [recommendList, setRecommendList] = useState<ContentItem[]>([])
  const [categories, setCategories] = useState<CategoryGroup[]>([])
  const [murmurs, setMurmurs] = useState<any[]>([])
  const [stats, setStats] = useState({ contentCount: 0, commentCount: 0 })
  const mountedRef = useRef(false)

  useEffect(() => {
    if (mountedRef.current) return
    mountedRef.current = true

    Promise.allSettled([
      fetchContentCategories(),
      fetchRecommendContent(),
      fetchLatestMurmur(5),
      fetchContentStats(),
    ]).then(async ([catRes, recRes, murRes, statsRes]) => {
      if (recRes.status === 'fulfilled') {
        setRecommendList(((recRes.value as any)?.data ?? []).map(normalize))
      }
      if (murRes.status === 'fulfilled') {
        setMurmurs(((murRes.value as any)?.data ?? []).map((m: any) => ({
          id: m.id,
          text: m.content ?? m.text ?? '',
          date: formatDate(m.createTime ?? m.date),
        })))
      }
      if (statsRes.status === 'fulfilled' && (statsRes.value as any)?.data) {
        setStats((statsRes.value as any).data)
      }

      const fallback = [
        { type: 'article', name: '文章', count: 0 },
        { type: 'game', name: '游戏', count: 0 },
        { type: 'study', name: '学习', count: 0 },
        { type: 'video', name: '视频', count: 0 },
      ]
      const cats = (catRes.status === 'fulfilled' && (catRes.value as any)?.data?.length > 0)
        ? (catRes.value as any).data
        : fallback
      const results = await Promise.allSettled(cats.map((c: any) => fetchContentByCategory(c.type)))
      setCategories(
        cats
          .map((cat: any, i: number) => ({
            type: cat.type,
            title: cat.name || cat.type,
            count: cat.count ?? 0,
            list: results[i].status === 'fulfilled'
              ? ((results[i] as any).value?.data ?? []).map(normalize).slice(0, 5)
              : [],
          }))
          .filter((c: CategoryGroup) => c.list.length > 0),
      )

      setTimeout(() => initFadeIn(), 150)
    })
  }, [])

  return (
    <div className="flex gap-6 mx-auto min-h-[calc(100vh-90px)] bg-canvas px-4 py-8 sm:px-6">
      {/* 主内容区 */}
      <div className="flex-1 min-w-0 rounded-xl border border-hairline p-5">
        {/* 推荐内容 */}
        {recommendList.length > 0 && (
          <section className="mb-10">
            <div className="mb-5 flex items-baseline justify-between border-b border-hairline pb-3">
              <h2 className="text-lg font-semibold text-body-strong">推荐内容</h2>
            </div>
            <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
              {recommendList.map((item) => (
                <Link
                  key={item.id}
                  to={`/content-detail/${item.contentType || item.category || 'article'}/${item.id}`}
                  className="group card-hover overflow-hidden rounded-xl border border-hairline bg-surface-card transition-shadow hover:shadow-md"
                >
                  <div className="relative aspect-video overflow-hidden bg-surface-soft">
                    {item.cover ? (
                      <img src={item.cover} alt={item.title} className="h-full w-full object-cover transition-transform group-hover:scale-105" />
                    ) : (
                      <div className="flex h-full items-center justify-center"><BookOpen className="h-8 w-8 text-muted-soft" /></div>
                    )}
                    <span className="absolute left-2 top-2 rounded-full bg-surface-dark/60 px-2 py-0.5 text-xs text-white">
                      {item.category || item.contentType}
                    </span>
                    <span className="absolute right-2 top-2 flex items-center gap-1 rounded-full bg-surface-dark/60 px-2 py-0.5 text-xs text-white">
                      <MessageCircle className="h-3 w-3" />{item.comments ?? 0}
                    </span>
                  </div>
                  <div className="p-4">
                    <h3 className="text-sm font-medium text-body-strong line-clamp-1">{item.title}</h3>
                    <p className="mt-1 text-xs text-muted line-clamp-2">{item.desc}</p>
                    <div className="mt-2 flex items-center gap-3 text-xs text-muted-soft">
                      {item.date && <span>{formatDate(item.date)}</span>}
                      <span>{item.comments ?? 0} 评论</span>
                    </div>
                  </div>
                </Link>
              ))}
            </div>
          </section>
        )}

        {/* 分类内容 */}
        {categories.map((cat) => (
          <section key={cat.type} className="mb-10 fade-in">
            <div className="mb-5 flex items-baseline justify-between border-b border-hairline pb-3">
              <h2 className="text-lg font-semibold text-body-strong">{cat.title}</h2>
              <span className="text-xs text-muted-soft">{cat.count} 篇</span>
            </div>
            <div className="space-y-4">
              {cat.list.map((item) => (
                <Link
                  key={item.id}
                  to={`/content-detail/${cat.type}/${item.id}`}
                  className="flex gap-4 rounded-lg p-2 transition-colors hover:bg-surface-soft"
                >
                  <div className="relative h-[72px] w-[120px] flex-shrink-0 overflow-hidden rounded-lg bg-surface-soft">
                    {item.cover ? (
                      <img src={item.cover} alt={item.title} className="h-full w-full object-cover" />
                    ) : (
                      <div className="flex h-full items-center justify-center"><BookOpen className="h-6 w-6 text-muted-soft" /></div>
                    )}
                    {cat.type === 'video' && (
                      <span className="absolute inset-0 flex items-center justify-center bg-black/30 text-white">
                        <svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor"><polygon points="5 3 19 12 5 21 5 3" /></svg>
                      </span>
                    )}
                  </div>
                  <div className="flex min-w-0 flex-1 flex-col justify-center">
                    <h3 className="text-sm font-medium text-body-strong line-clamp-1">{item.title}</h3>
                    <p className="mt-1 text-xs text-muted line-clamp-2">{item.desc}</p>
                    <div className="mt-1 flex items-center gap-3 text-xs text-muted-soft">
                      {item.date && <span>{formatDate(item.date)}</span>}
                      <span className="flex items-center gap-0.5">
                        <MessageCircle className="h-3 w-3" />{item.comments ?? 0}
                      </span>
                    </div>
                  </div>
                </Link>
              ))}
            </div>
          </section>
        ))}
      </div>

      {/* 右侧边栏 */}
      <aside className="hidden w-[260px] flex-shrink-0 lg:block">
        {/* 个人信息卡 */}
        <div className="fade-in mb-4 rounded-xl border border-hairline bg-surface-card p-5 text-center">
          <img src={defaultAvatar} alt="YoyuEN" className="mx-auto h-16 w-16 rounded-full object-cover" />
          <div className="mt-3 font-semibold text-body-strong">YoyuEN</div>
          <div className="mt-1 text-xs text-muted">宁鸣而死，不默而生</div>
          <p className="mt-2 text-xs leading-relaxed text-muted">
            北方民族大学 · 软件工程<br />
            热爱技术、游戏与生活
          </p>
          <div className="mt-3 flex justify-center gap-6 border-t border-hairline pt-3">
            <div className="text-center">
              <div className="text-sm font-semibold text-body-strong">{stats.contentCount}</div>
              <div className="text-xs text-muted-soft">文章</div>
            </div>
            <div className="w-px bg-hairline" />
            <div className="text-center">
              <div className="text-sm font-semibold text-body-strong">{stats.commentCount}</div>
              <div className="text-xs text-muted-soft">评论</div>
            </div>
          </div>
        </div>

        {/* 每日碎碎念 */}
        {murmurs.length > 0 && (
          <div className="fade-in rounded-xl border border-hairline bg-surface-card p-5">
            <h3 className="mb-3 text-sm font-semibold text-body-strong">每日碎碎念</h3>
            <div className="space-y-3">
              {murmurs.map((m: any) => (
                <div key={m.id} className="border-b border-hairline-soft pb-2 last:border-0 last:pb-0">
                  <p className="text-xs text-body leading-relaxed">{m.text}</p>
                  <span className="text-xs text-muted-soft">{m.date}</span>
                </div>
              ))}
            </div>
          </div>
        )}
      </aside>
    </div>
  )
}
