// Fronted/src/views/Diary.vue
<template>
  <div class="diary-container">
    <DiarySwiper :diary-entries="diaryEntries" />
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { ElMessage } from 'element-plus'
import DiarySwiper from '@/components/DiarySwiper.vue'
import { fetchDiaryList } from '@/api/diary/diary.js'

const diaryEntries = ref([])
const loading = ref(false)

const loadDiaryData = async () => {
  loading.value = true
  try {
    const res = await fetchDiaryList('diary')
    diaryEntries.value = (res.data || []).map(item => ({
      date: item.diaryDate || '',
      weather: item.weather || '',
      mood: item.mood || '',
      avatar: item.avatar || '/src/assets/picture/YoyuEN.png',
      content: item.content || ''
    }))
  } catch (e) {
    console.error('获取日记数据失败', e)
    ElMessage.error('获取日记数据失败')
  } finally {
    loading.value = false
  }
}

onMounted(() => {
  loadDiaryData()
})
</script>

<style scoped>
.diary-container {
  min-height: 100vh;
  background: #fff;
  padding: 100px 24px 60px;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 24px;
}

@media (max-width: 768px) {
  .diary-container {
    padding: 80px 16px 40px;
  }
}
</style>

// white_fronted/src/views/Diary.tsx
import { useEffect, useState } from 'react'
import DiarySwiper from '@/components/DiarySwiper'
import { fetchDiaryList } from '@/api/diary'
import defaultAvatar from '@/assets/picture/YoyuEN.png'

export default function Diary() {
  const [entries, setEntries] = useState<any[]>([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    fetchDiaryList('diary')
      .then((res: any) => {
        const data = res?.data ?? []
        setEntries(data.map((item: any) => ({
          date: item.diaryDate ?? '',
          weather: item.weather ?? '',
          mood: item.mood ?? '',
          avatar: item.avatar || defaultAvatar,
          content: item.content ?? '',
        })))
      })
      .catch(() => {})
      .finally(() => setLoading(false))
  }, [])

  return (
    <div className="flex min-h-screen flex-col items-center justify-center gap-6 bg-canvas px-4 py-24 sm:px-6">
      {loading ? (
        <div className="flex flex-col items-center gap-3">
          <div className="h-8 w-8 animate-spin rounded-full border-2 border-primary border-t-transparent" />
          <p className="text-sm text-muted">加载中...</p>
        </div>
      ) : (
        <DiarySwiper diaryEntries={entries} />
      )}
    </div>
  )
}
