// Fronted/src/views/admin/Statistics.vue
<template>
  <section>
    <!-- 汇总卡片 -->
    <el-row :gutter="16" style="margin-bottom: 20px;">
      <el-col :xs="12" :sm="6" v-for="card in summaryCards" :key="card.label">
        <div class="summary-card">
          <el-icon :size="22" class="summary-icon">
            <component :is="card.icon" />
          </el-icon>
          <div class="summary-value">{{ card.value }}</div>
          <div class="summary-label">{{ card.label }}</div>
        </div>
      </el-col>
    </el-row>

    <!-- 活动热力图 + 分类分布 -->
    <el-row :gutter="16">
      <el-col :xs="24" :md="16">
        <el-card class="chart-card" v-loading="heatmapLoading">
          <div class="card-title">内容发布热力图（近一年）</div>
          <div class="heatmap-wrap">
            <CalendarHeatmap
              v-if="heatmapValues.length"
              :values="heatmapValues"
              :end-date="today"
              :max="heatmapMax"
              :round="3"
              tooltip-unit="篇"
              :color="{ empty: '#ebedf0', colors: ['#c6e8a6', '#8cc665', '#44a340', '#1e6823'] }"
            />
            <div v-else class="empty-chart">暂无数据</div>
          </div>
        </el-card>
      </el-col>

      <el-col :xs="24" :md="8">
        <el-card class="chart-card" v-loading="categoryLoading">
          <div class="card-title">内容分类分布</div>
          <div class="donut-wrap">
            <svg v-if="categoryData.length" class="donut-svg" viewBox="0 0 120 120">
              <circle
                v-for="(seg, i) in donutSegments"
                :key="i"
                cx="60" cy="60" r="40"
                fill="none"
                :stroke="seg.color"
                stroke-width="20"
                :stroke-dasharray="`${seg.dash} ${seg.gap}`"
                :stroke-dashoffset="seg.offset"
              />
              <text x="60" y="56" text-anchor="middle" font-size="11" fill="#606266" font-weight="500">总计</text>
              <text x="60" y="70" text-anchor="middle" font-size="14" fill="#303133" font-weight="700">{{ totalContent }}</text>
            </svg>
            <div v-else class="empty-chart">暂无数据</div>
          </div>
          <div class="legend-list">
            <div v-for="(item, i) in categoryData" :key="i" class="legend-item">
              <span class="legend-dot" :style="{ background: categoryColors[i % categoryColors.length] }"></span>
              <span class="legend-name">{{ categoryLabel(item.name) }}</span>
              <span class="legend-value">{{ item.count }}</span>
            </div>
          </div>
        </el-card>
      </el-col>
    </el-row>
  </section>
</template>

<script setup>
import { onMounted, ref, computed, onUnmounted } from 'vue'
import { ElMessage } from 'element-plus'
import { TrendCharts, Refresh, Document, ChatDotRound, View, Star } from '@element-plus/icons-vue'
import { CalendarHeatmap } from 'vue3-calendar-heatmap'
import 'vue3-calendar-heatmap/dist/style.css'
import { fetchActivityStats, fetchContentStats, fetchAllContent } from '@/api/content/content'

const loading = ref(false)
const heatmapLoading = ref(false)
const categoryLoading = ref(false)

const today = new Date().toISOString().slice(0, 10)

// 汇总数据
const totalContent = ref(0)
const totalComment = ref(0)
const totalViews = ref(0)
const totalRecommend = ref(0)

const summaryCards = computed(() => [
  { label: '内容总数', value: totalContent.value, icon: Document },
  { label: '评论总数', value: totalComment.value, icon: ChatDotRound },
  { label: '总浏览量', value: totalViews.value, icon: View },
  { label: '推荐内容', value: totalRecommend.value, icon: Star },
])

// 热力图
const heatmapValues = ref([])
const heatmapMax = ref(5)

// 分类分布
const categoryColors = ['#667eea', '#f5576c', '#4facfe', '#43e97b', '#f093fb', '#f6d365']
const categoryData = ref([])

const categoryLabel = (name) => {
  const map = { article: '文章', game: '游戏', study: '学习', video: '视频' }
  return map[name] || name
}

const donutSegments = computed(() => {
  const total = categoryData.value.reduce((s, c) => s + c.count, 0)
  if (!total) return []
  const circumference = 2 * Math.PI * 40 // r=40
  let offset = 0
  return categoryData.value.map((item, i) => {
    const ratio = item.count / total
    const dash = ratio * circumference
    const seg = {
      color: categoryColors[i % categoryColors.length],
      dash,
      gap: circumference - dash,
      offset: circumference * 0.25 - offset, // 从顶部开始
    }
    offset += dash
    return seg
  })
})

// 加载汇总 + 浏览量/推荐数（从 allContent 聚合）
const loadSummary = async () => {
  const [statsRes, allRes] = await Promise.all([
    fetchContentStats(),
    fetchAllContent({}),
  ])
  const stats = statsRes.data || {}
  totalContent.value = stats.contentCount || 0
  totalComment.value = stats.commentCount || 0

  const allList = allRes.data || []
  totalViews.value = allList.reduce((s, c) => s + (c.viewCount || 0), 0)
  totalRecommend.value = allList.filter(c => c.isRecommend).length

  // 分类统计
  const catMap = {}
  allList.forEach(c => {
    catMap[c.category] = (catMap[c.category] || 0) + 1
  })
  categoryData.value = Object.entries(catMap)
    .map(([name, count]) => ({ name, count }))
    .sort((a, b) => b.count - a.count)
}

// 加载热力图（近一年）
const loadHeatmap = async () => {
  heatmapLoading.value = true
  try {
    const res = await fetchActivityStats(365)
    const map = res.data || {}
    heatmapValues.value = Object.entries(map).map(([date, count]) => ({ date, count }))
    heatmapMax.value = Math.max(...Object.values(map), 1)
  } finally {
    heatmapLoading.value = false
  }
}

const loadData = async () => {
  loading.value = true
  categoryLoading.value = true
  try {
    await Promise.all([loadSummary(), loadHeatmap()])
  } catch (e) {
    ElMessage.error(e.message || '加载失败')
  } finally {
    loading.value = false
    categoryLoading.value = false
  }
}

const handleAdminRefresh = () => {
  loadData()
}

onMounted(() => {
  loadData()
  window.addEventListener('admin-refresh', handleAdminRefresh)
})

onUnmounted(() => {
  window.removeEventListener('admin-refresh', handleAdminRefresh)
})
</script>

<style scoped>
.summary-card {
  border-radius: 8px;
  padding: 20px 16px;
  display: flex;
  flex-direction: column;
  gap: 8px;
  margin-bottom: 16px;
  background: #fff;
  border: 1px solid #ebeef5;
  box-shadow: 0 1px 4px rgba(0, 0, 0, 0.06);
  transition: box-shadow 0.2s;
}
.summary-card:hover {
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
}
.summary-icon {
  color: #909399;
}
.summary-value {
  font-size: 28px;
  font-weight: 700;
  letter-spacing: -0.5px;
  line-height: 1;
  color: #303133;
}
.summary-label {
  font-size: 13px;
  color: #909399;
}

.chart-card {
  border-radius: 12px;
  box-shadow: 0 2px 12px rgba(0, 0, 0, 0.08);
}
.chart-card :deep(.el-card__body) {
  padding: 20px;
}
.card-title {
  font-size: 14px;
  font-weight: 600;
  color: #303133;
  margin-bottom: 16px;
}

/* 热力图 */
.heatmap-wrap {
  overflow-x: auto;
  padding-bottom: 4px;
}
.heatmap-wrap :deep(.vch__container) {
  width: 100%;
}

/* 甜甜圈图 */
.donut-wrap {
  display: flex;
  justify-content: center;
  margin-bottom: 12px;
}
.donut-svg {
  width: 120px;
  height: 120px;
}
.legend-list {
  display: flex;
  flex-direction: column;
  gap: 8px;
}
.legend-item {
  display: flex;
  align-items: center;
  font-size: 13px;
  color: #606266;
}
.legend-dot {
  width: 10px;
  height: 10px;
  border-radius: 50%;
  margin-right: 8px;
  flex-shrink: 0;
}
.legend-name {
  flex: 1;
}
.legend-value {
  font-weight: 600;
  color: #303133;
}

.empty-chart {
  height: 100px;
  display: flex;
  align-items: center;
  justify-content: center;
  color: #c0c4cc;
  font-size: 13px;
}
</style>

// white_fronted/src/views/admin/Statistics.tsx
import { useEffect, useMemo, useState } from 'react'
import { FileText, MessageCircle, Eye, Star } from 'lucide-react'
import { fetchContentStats, fetchAllContent } from '@/api/content'
import Heatmap from '@/components/Heatmap'

const CAT_LABELS: Record<string, string> = { article: '文章', game: '游戏', study: '学习', video: '视频' }

export default function Statistics() {
  const [stats, setStats] = useState<any>({})
  const [allContent, setAllContent] = useState<any[]>([])
  const [loading, setLoading] = useState(true)

  const loadData = async () => {
    setLoading(true)
    try {
      const [statsRes, contentRes]: any[] = await Promise.allSettled([
        fetchContentStats(),
        fetchAllContent(),
      ])
      if (statsRes.status === 'fulfilled') setStats(statsRes.value?.data ?? {})
      if (contentRes.status === 'fulfilled') setAllContent(contentRes.value?.data ?? [])
    } catch {}
    setLoading(false)
  }

  useEffect(() => {
    loadData()
    window.addEventListener('admin-refresh', loadData)
    return () => window.removeEventListener('admin-refresh', loadData)
  }, [])

  const totalViews = useMemo(() => allContent.reduce((s, c) => s + (c.viewCount ?? 0), 0), [allContent])
  const totalRecommend = useMemo(() => allContent.filter((c) => c.isRecommended || c.recommend).length, [allContent])

  // Category distribution
  const catDist = useMemo(() => {
    const map: Record<string, number> = {}
    allContent.forEach((c) => {
      const cat = c.category || c.contentType || 'article'
      map[cat] = (map[cat] || 0) + 1
    })
    return Object.entries(map).sort((a, b) => b[1] - a[1])
  }, [allContent])

  const total = catDist.reduce((s, [, n]) => s + n, 0)

  // Donut SVG
  const donutSegments = useMemo(() => {
    const circumference = 2 * Math.PI * 40
    let offset = circumference * 0.25 // start at top
    return catDist.map(([cat, count], i) => {
      const len = total > 0 ? (count / total) * circumference : 0
      const seg = { cat, count, len, offset, color: `var(--color-${i})` }
      offset -= len
      return seg
    })
  }, [catDist, total])

  const summaryCards = [
    { label: '内容总数', value: stats.contentCount ?? allContent.length ?? 0, icon: FileText, color: 'text-accent-teal' },
    { label: '评论总数', value: stats.commentCount ?? 0, icon: MessageCircle, color: 'text-accent-amber' },
    { label: '总浏览量', value: totalViews, icon: Eye, color: 'text-primary' },
    { label: '推荐内容', value: totalRecommend, icon: Star, color: 'text-muted' },
  ]

  return (
    <div className="p-6">
      <h1 className="mb-6 text-xl font-semibold text-body-strong">数据统计</h1>

      {loading ? (
        <div className="flex justify-center py-20"><div className="h-8 w-8 animate-spin rounded-full border-2 border-primary border-t-transparent" /></div>
      ) : (
        <>
          {/* 概览卡片 */}
          <div className="mb-8 grid grid-cols-2 gap-4 sm:grid-cols-4">
            {summaryCards.map(({ label, value, icon: Icon, color }) => (
              <div key={label} className="rounded-xl border border-hairline bg-surface-card p-5">
                <div className="flex items-center gap-3">
                  <div className={`rounded-lg bg-surface-soft p-2.5 ${color}`}>
                    <Icon className="h-5 w-5" />
                  </div>
                  <div>
                    <div className="text-2xl font-bold text-body-strong">{value}</div>
                    <div className="text-xs text-muted-soft">{label}</div>
                  </div>
                </div>
              </div>
            ))}
          </div>

          <div className="grid gap-6 lg:grid-cols-3">
            {/* 热力图 */}
            <div className="lg:col-span-2 rounded-xl border border-hairline bg-surface-card p-5">
              <h3 className="mb-2 text-sm font-semibold text-body-strong">内容活跃度</h3>
              <Heatmap />
            </div>

            {/* 分类分布 */}
            <div className="rounded-xl border border-hairline bg-surface-card p-5">
              <h3 className="mb-4 text-sm font-semibold text-body-strong">内容分类分布</h3>
              <div className="flex items-center justify-center">
                <svg width="200" height="200" viewBox="0 0 100 100">
                  {donutSegments.map((seg, i) => (
                    <circle
                      key={seg.cat}
                      cx="50" cy="50" r="40"
                      fill="none"
                      stroke={`var(--color-${i})`}
                      strokeWidth="16"
                      strokeDasharray={`${seg.len} ${2 * Math.PI * 40 - seg.len}`}
                      strokeDashoffset={seg.offset}
                      transform="rotate(-90 50 50)"
                      className="transition-all duration-500"
                    />
                  ))}
                  <circle cx="50" cy="50" r="30" fill="currentColor" className="text-surface-card" />
                  <text x="50" y="50" textAnchor="middle" dominantBaseline="central" className="fill-body-strong text-xs font-bold" fontSize="14">
                    {total}
                  </text>
                </svg>
              </div>
              <div className="mt-4 space-y-2">
                {catDist.map(([cat, count], i) => (
                  <div key={cat} className="flex items-center justify-between text-xs">
                    <div className="flex items-center gap-2">
                      <span className="h-2.5 w-2.5 rounded-full" style={{ backgroundColor: `var(--color-${i})` }} />
                      <span className="text-body">{CAT_LABELS[cat] || cat}</span>
                    </div>
                    <span className="text-muted-soft">{count}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>

          <style>{`
            :root { --color-0: #5db8a6; --color-1: #e8a55a; --color-2: #cc785c; --color-3: #8e8b82; }
          `}</style>
        </>
      )}
    </div>
  )
}
