// Fronted/src/components/ContextMenu.vue
<template>
  <teleport to="body">
    <transition name="context-menu-fade">
      <div
        v-if="visible"
        class="context-menu-overlay"
        @click="close"
        @contextmenu.prevent
      >
        <div
          class="context-menu"
          :style="menuStyle"
          @click.stop
        >
          <div v-if="title" class="context-menu-title">{{ title }}</div>
          <div class="context-menu-content">
            <slot></slot>
          </div>
          <div v-if="actions.length" class="context-menu-actions">
            <button
              v-for="(action, index) in actions"
              :key="index"
              class="context-menu-action"
              :class="{ danger: action.danger }"
              @click="handleAction(action)"
            >
              <el-icon v-if="action.icon"><component :is="action.icon" /></el-icon>
              {{ action.label }}
            </button>
          </div>
        </div>
      </div>
    </transition>
  </teleport>
</template>

<script setup>
import { ref, computed } from 'vue'

const props = defineProps({
  title: String,
  actions: {
    type: Array,
    default: () => []
  }
})

const emit = defineEmits(['close'])

const visible = ref(false)
const position = ref({ x: 0, y: 0 })

const menuStyle = computed(() => {
  return {
    left: `${position.value.x}px`,
    top: `${position.value.y}px`
  }
})

const show = (x, y) => {
  position.value = { x, y }
  visible.value = true

  // 调整位置避免超出屏幕
  setTimeout(() => {
    const menu = document.querySelector('.context-menu')
    if (!menu) return

    const rect = menu.getBoundingClientRect()
    const viewportWidth = window.innerWidth
    const viewportHeight = window.innerHeight

    if (rect.right > viewportWidth) {
      position.value.x = viewportWidth - rect.width - 10
    }
    if (rect.bottom > viewportHeight) {
      position.value.y = viewportHeight - rect.height - 10
    }
  }, 0)
}

const close = () => {
  visible.value = false
  emit('close')
}

const handleAction = (action) => {
  action.handler?.()
  close()
}

defineExpose({ show, close })
</script>

<style scoped>
.context-menu-overlay {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  z-index: 9999;
  background: rgba(0, 0, 0, 0.1);
}

.context-menu {
  position: fixed;
  background: white;
  border-radius: 8px;
  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.15);
  min-width: 200px;
  max-width: 400px;
  max-height: 80vh;
  overflow: auto;
  z-index: 10000;
}

.context-menu-title {
  padding: 12px 16px;
  font-weight: 600;
  font-size: 14px;
  border-bottom: 1px solid #f0f0f0;
  color: #303133;
}

.context-menu-content {
  padding: 12px 16px;
  font-size: 13px;
  color: #606266;
  line-height: 1.6;
  max-height: 300px;
  overflow-y: auto;
}

.context-menu-actions {
  border-top: 1px solid #f0f0f0;
  padding: 8px;
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.context-menu-action {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 8px 12px;
  border: none;
  background: transparent;
  color: #606266;
  font-size: 13px;
  cursor: pointer;
  border-radius: 4px;
  transition: all 0.2s;
  text-align: left;
}

.context-menu-action:hover {
  background: #f5f7fa;
  color: #409eff;
}

.context-menu-action.danger {
  color: #f56c6c;
}

.context-menu-action.danger:hover {
  background: #fef0f0;
}

.context-menu-fade-enter-active,
.context-menu-fade-leave-active {
  transition: opacity 0.2s;
}

.context-menu-fade-enter-from,
.context-menu-fade-leave-to {
  opacity: 0;
}
</style>

// white_fronted/src/components/ContextMenu.tsx
import React, { useCallback, useEffect, useRef, useState } from 'react'
import { createPortal } from 'react-dom'
import { cn } from '@/lib/utils'

interface ContextMenuAction {
  label: string
  icon?: React.ReactNode
  danger?: boolean
  handler: () => void
}

interface ContextMenuProps {
  title?: string
  actions?: ContextMenuAction[]
  children?: React.ReactNode
}

export interface ContextMenuHandle {
  show: (x: number, y: number) => void
  close: () => void
}

function ContextMenuInner(
  { title, actions = [], children }: ContextMenuProps,
  ref: React.Ref<ContextMenuHandle>,
) {
  const [visible, setVisible] = useState(false)
  const [pos, setPos] = useState({ x: 0, y: 0 })
  const menuRef = useRef<HTMLDivElement | null>(null)

  const close = useCallback(() => setVisible(false), [])

  const show = useCallback((x: number, y: number) => {
    setPos({ x, y })
    setVisible(true)

    // adjust position to avoid overflow
    requestAnimationFrame(() => {
      const menu = menuRef.current
      if (!menu) return
      const rect = menu.getBoundingClientRect()
      const vw = window.innerWidth
      const vh = window.innerHeight

      setPos((prev) => ({
        x: rect.right > vw ? vw - rect.width - 10 : prev.x,
        y: rect.bottom > vh ? vh - rect.height - 10 : prev.y,
      }))
    })
  }, [])

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') close()
    }
    if (visible) {
      document.addEventListener('keydown', onKey)
      return () => document.removeEventListener('keydown', onKey)
    }
  }, [visible, close])

  React.useImperativeHandle(ref, () => ({ show, close }), [show, close])

  if (!visible) return null

  return createPortal(
    <div
      className="fixed inset-0 z-[9999] bg-black/10"
      onClick={close}
      onContextMenu={(e) => e.preventDefault()}
    >
      <div
        ref={menuRef}
        className="fixed z-[10000] min-w-[200px] max-w-[400px] max-h-[80vh] overflow-auto rounded-lg bg-canvas shadow-lg border border-hairline"
        style={{ left: pos.x, top: pos.y }}
        onClick={(e) => e.stopPropagation()}
      >
        {title && (
          <div className="border-b border-hairline px-4 py-3 text-sm font-semibold text-body-strong">
            {title}
          </div>
        )}
        {children && (
          <div className="px-4 py-3 text-sm text-body leading-relaxed max-h-[300px] overflow-y-auto">
            {children}
          </div>
        )}
        {actions.length > 0 && (
          <div className="border-t border-hairline flex flex-col gap-1 p-2">
            {actions.map((action, i) => (
              <button
                key={i}
                type="button"
                onClick={() => {
                  action.handler()
                  close()
                }}
                className={cn(
                  'flex items-center gap-2 rounded px-3 py-2 text-left text-sm transition-colors',
                  action.danger
                    ? 'text-error hover:bg-error/10'
                    : 'text-body hover:bg-surface-soft hover:text-primary',
                )}
              >
                {action.icon}
                {action.label}
              </button>
            ))}
          </div>
        )}
      </div>
    </div>,
    document.body,
  )
}

const ContextMenu = React.forwardRef(ContextMenuInner)
export default ContextMenu
